# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  # using major version aliases

  # aliased to a recent 7.x version
  - 7.0

# optionally set up exclutions and allowed failures in the matrix
matrix:
  exclude:
    - php: hhvm
      env: DB=pgsql  # PDO driver for pgsql is unsupported by HHVM (3rd party install for support)
  allow_failures:
    - php: 7.0

befor_script:
  - if [[ "$TRAVIS_PHP_VERSION" == '5.6' ]]; then composer install -n ; fi 
  - if [[ "$TRAVIS_PHP_VERSION" != '7.0' ]]; then composer install -n ; fi
script: phpunit --configuration phpunit.xml --coverage-text

# configure notifications (email, IRC, campfire etc)
notifications:
  irc: "irc.freenode.org#yourfavouriteroomfortravis"
